# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the multiples of 3 or 5 below 1000.
#
# @author  Rudd Fawcett
# @since 2015-11-26

first, second = 1, 2
sum, max = second, 4000000

while sum <= max
  third = first + second
  first = second
  second = third

  if third % 2 == 0
    sum += third
  end
end

print sum
